const produtos = [
  {
    id: 1,
    nome: "Suporte Apple Watch",
    preco: 24.99,
    categoria: "Suportes",
    tags: ["suportes", "até 30 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis", "Diversos Modelos"],
    descricao: "Suporte para Apple Watch, prático e elegante para sua mesa.",
    imagens: ["imgs/suportes/SuporteCarregadorApplewatch.jpg"]
  },
  {
    id: 2,
    nome: "Suporte iPhone",
    preco: 49.99,
    categoria: "Suportes",
    tags: ["suportes", "até 50 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis", "Diversos Modelos"],
    descricao: "Suporte para iPhone, ideal para mesa ou escritório.",
    imagens: ["imgs/suportes/SuporteIphone.jpg"]
  },
  {
    id: 3,
    nome: "Suporte Hot Wheels 4 carrinhos (modular)",
    preco: 21.99,
    categoria: "Suportes",
    tags: ["suportes", "até 30 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Suporte modular para 4 carrinhos Hot Wheels. Pode ser expandido até 5!",
    imagens: ["imgs/suportes/SuporteHotWhells.jpg"]
  },
  {
    id: 4,
    nome: "Suporte Jogo de Cartas",
    preco: 39.99,
    categoria: "Suportes",
    tags: ["suportes", "até 40 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Suporte organizador para baralho e jogos de cartas.",
    imagens: ["imgs/suportes/jogosCartas_1.jpg", "imgs/suportes/jogosCartas_2.jpg", "imgs/suportes/jogosCartas_3.jpg", "imgs/suportes/jogosCartas_4.jpg"]
  },
  {
    id: 5,
    nome: "Vaso Estilo Lego 15cm",
    preco: 59.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 60 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Vaso decorativo estilo Lego com 15cm de altura. Charmoso e divertido.",
    imagens: ["imgs/utilidades/vasoEstiloLego15cm.jpg"]
  },
  {
    id: 6,
    nome: "Vaso Carinha Coração 6cm",
    preco: 31.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 40 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Vasinho fofo com carinha de coração, 6cm de diâmetro. Perfeito para suculentas.",
    imagens: ["imgs/utilidades/vasoCarinhaCoracao6cm.jpg"]
  },
  {
    id: 7,
    nome: "Kit Porta Copos (6un) + Porta Guardanapos Costela de Adão",
    preco: 72.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 80 reais", "kit"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Kit com 6 porta copos com estampa de Costela de Adão combinado com o porta guardanapos. Decorativo e funcional.",
    imagens: ["imgs/kits/KitCostelaAdao.jpg"]
  },
    {
    id: 8,
    nome: "Kit Porta Copos Costela de Adão (6un) + base",
    preco: 63.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 70 reais", "kit"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Kit com 6 porta copos com estampa de Costela de Adão. Decorativo e funcional.",
    imagens: ["imgs/kits/KitCostelaAdao.jpg"]
  },
  {
    id: 9,
    nome: "Porta Guardanapos Costela de Adão",
    preco: 17.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 20 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Porta guardanapos com estampa de Costela de Adão. Lindo para a mesa de jantar.",
    imagens: ["imgs/kits/KitCostelaAdao.jpg"]
  },
  {
    id: 10,
    nome: "Porta Copos Sakurá (6un) + base",
    preco: 63.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 70 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Kit com 6 porta copos com estampa de Sakurá. Delicado e elegante.",
    imagens: ["imgs/utilidades/PortaCoposSakura_1.jpg", "imgs/utilidades/PortaCoposSakura_2.jpg", "imgs/utilidades/PortaCoposSakura_3.jpg"]
  },
  {
    id: 11,
    nome: "Porta Foto Tulipa",
    preco: 15.00,
    categoria: "Utilidades",
    tags: ["utilidades", "até 20 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Porta foto em formato de tulipa. Perfeito para guardar memórias especiais.",
    imagens: ["imgs/utilidades/PortaFotosTulipa_1.jpg", "imgs/utilidades/PortaFotosTulipa_2.jpg", "imgs/utilidades/PortaFotosTulipa_3.jpg", "imgs/utilidades/PortaFotosTulipa_4.jpg", "imgs/utilidades/PortaFotosTulipa_5.jpg", "imgs/utilidades/PortaFotosTulipa_6.jpg", ]
  },
  {
    id: 12,
    nome: "Vaso Elegante 15cm",
    preco: 49.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 50 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Vaso elegante com 15cm de altura, design sofisticado para qualquer ambiente.",
    imagens: ["imgs/utilidades/VasoElegante15cm.jpg"]
  },
  {
    id: 13,
    nome: "Quadro Cristão",
    preco: 54.99,
    categoria: "Religiosos",
    tags: ["Religiosos", "até 60 reais"],
    material: "PLA",
    cores: ["Marrom com branco e preto"],
    descricao: "Quadro decorativo com tema cristão. Lindo para presentear ou decorar.",
    imagens: ["imgs/religiosos/QuadroCristao_1.jpg"]
  },
  {
    id: 14,
    nome: "Marcador de Livro Cristão (kit 5un)",
    preco: 10.00,
    categoria: "Religiosos",
    tags: ["Religiosos", "até 10 reais", "kit"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Kit com 5 marcadores de livro com tema cristão. Ótimo para presentear.",
    imagens: ["imgs/religiosos/marcadorCristao_1.jpg", "imgs/religiosos/marcadorCristao_2.jpeg"]
  },
  {
    id: 15,
    nome: "Nossa Senhora Aparecida 7cm",
    preco: 19.99,
    categoria: "Religiosos",
    tags: ["Religiosos", "até 20 reais"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Imagem de Nossa Senhora Aparecida com 7cm. Delicada e cheia de fé.",
    imagens: ["imgs/religiosos/NossaSenhoraAparecida7cm_1.jpg", "imgs/religiosos/NossaSenhoraAparecida7cm_2.jpg"]
  },
  {
    id: 16,
    nome: "Chaveiro Fé",
    preco: 9.50,
    categoria: "Chaveiros",
    tags: ["Chaveiros", "até 10 reais", "Religiosos"],
    material: "PLA",
    cores: ["Marrom com branco"],
    descricao: "Chaveiro com a palavra Fé em relevo. Singelo e cheio de significado.",
    imagens: ["imgs/chaveiros/ChaveiroFe.jpeg"]
  },
  {
    id: 17,
    nome: "Porta Óculos Gatinho",
    preco: 49.99,
    categoria: "Utilidades",
    tags: ["utilidades", "até 50 reais", "Presentes"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Porta óculos em formato de gatinho. Fofinho e funcional para sua mesa.",
    imagens: ["imgs/utilidades/PortaOculosGatinho_1.jpg", "imgs/utilidades/PortaOculosGatinho_2.jpg"]
  },
  {
    id: 18,
    nome: "Porta canetas Engrenagem",
    preco: 39.99,
    categoria: "Escritório",
    tags: ["Escritório", "até 40 reais", "Presentes"],
    material: "PLA",
    cores: ["Diversas cores disponíveis"],
    descricao: "Porta canetas em formato de engrenagem móvel. Perfeito para presentear.",
    imagens: ["imgs/Escritorio/PortaCanetasEngrenagens.jpg"]
  }
];